# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import payout_pb2 as payout__pb2


class PayoutStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFlatFees = channel.unary_unary(
                '/main.Payout/GetFlatFees',
                request_serializer=payout__pb2.TenantId.SerializeToString,
                response_deserializer=payout__pb2.FlatFeesResponse.FromString,
                )
        self.CreateFlatFees = channel.unary_unary(
                '/main.Payout/CreateFlatFees',
                request_serializer=payout__pb2.FlatFeesRequest.SerializeToString,
                response_deserializer=payout__pb2.StatusResponse.FromString,
                )
        self.GetCalculationAttributes = channel.unary_unary(
                '/main.Payout/GetCalculationAttributes',
                request_serializer=payout__pb2.TenantId.SerializeToString,
                response_deserializer=payout__pb2.CalculationAttributesResponse.FromString,
                )
        self.GetParameterValue = channel.unary_unary(
                '/main.Payout/GetParameterValue',
                request_serializer=payout__pb2.TenantId.SerializeToString,
                response_deserializer=payout__pb2.ParameterValueResponse.FromString,
                )
        self.DeleteFlatFees = channel.unary_unary(
                '/main.Payout/DeleteFlatFees',
                request_serializer=payout__pb2.DeleteFlatFeeRequest.SerializeToString,
                response_deserializer=payout__pb2.StatusResponse.FromString,
                )
        self.GetMarketPlaceFees = channel.unary_unary(
                '/main.Payout/GetMarketPlaceFees',
                request_serializer=payout__pb2.TenantId.SerializeToString,
                response_deserializer=payout__pb2.MarketPlaceFeeResponse.FromString,
                )
        self.GetColumnsForMarketPlaceFees = channel.unary_unary(
                '/main.Payout/GetColumnsForMarketPlaceFees',
                request_serializer=payout__pb2.TenantId.SerializeToString,
                response_deserializer=payout__pb2.ColumnsResponse.FromString,
                )
        self.CreateMarketPlaceFees = channel.unary_unary(
                '/main.Payout/CreateMarketPlaceFees',
                request_serializer=payout__pb2.MarketPlaceFeeRequest.SerializeToString,
                response_deserializer=payout__pb2.StatusResponse.FromString,
                )
        self.DeleteMarketPlaceFees = channel.unary_unary(
                '/main.Payout/DeleteMarketPlaceFees',
                request_serializer=payout__pb2.DeleteFlatFeeRequest.SerializeToString,
                response_deserializer=payout__pb2.StatusResponse.FromString,
                )
        self.CreatePromotions = channel.unary_unary(
                '/main.Payout/CreatePromotions',
                request_serializer=payout__pb2.PromotionsRequest.SerializeToString,
                response_deserializer=payout__pb2.StatusResponse.FromString,
                )
        self.GetPromotions = channel.unary_unary(
                '/main.Payout/GetPromotions',
                request_serializer=payout__pb2.TenantId.SerializeToString,
                response_deserializer=payout__pb2.PromotionsResponse.FromString,
                )
        self.DeletePromotions = channel.unary_unary(
                '/main.Payout/DeletePromotions',
                request_serializer=payout__pb2.DeletePromotion.SerializeToString,
                response_deserializer=payout__pb2.StatusResponse.FromString,
                )


class PayoutServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFlatFees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFlatFees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalculationAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParameterValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFlatFees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketPlaceFees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetColumnsForMarketPlaceFees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMarketPlaceFees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMarketPlaceFees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePromotions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromotions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePromotions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayoutServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFlatFees': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlatFees,
                    request_deserializer=payout__pb2.TenantId.FromString,
                    response_serializer=payout__pb2.FlatFeesResponse.SerializeToString,
            ),
            'CreateFlatFees': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFlatFees,
                    request_deserializer=payout__pb2.FlatFeesRequest.FromString,
                    response_serializer=payout__pb2.StatusResponse.SerializeToString,
            ),
            'GetCalculationAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalculationAttributes,
                    request_deserializer=payout__pb2.TenantId.FromString,
                    response_serializer=payout__pb2.CalculationAttributesResponse.SerializeToString,
            ),
            'GetParameterValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameterValue,
                    request_deserializer=payout__pb2.TenantId.FromString,
                    response_serializer=payout__pb2.ParameterValueResponse.SerializeToString,
            ),
            'DeleteFlatFees': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFlatFees,
                    request_deserializer=payout__pb2.DeleteFlatFeeRequest.FromString,
                    response_serializer=payout__pb2.StatusResponse.SerializeToString,
            ),
            'GetMarketPlaceFees': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketPlaceFees,
                    request_deserializer=payout__pb2.TenantId.FromString,
                    response_serializer=payout__pb2.MarketPlaceFeeResponse.SerializeToString,
            ),
            'GetColumnsForMarketPlaceFees': grpc.unary_unary_rpc_method_handler(
                    servicer.GetColumnsForMarketPlaceFees,
                    request_deserializer=payout__pb2.TenantId.FromString,
                    response_serializer=payout__pb2.ColumnsResponse.SerializeToString,
            ),
            'CreateMarketPlaceFees': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMarketPlaceFees,
                    request_deserializer=payout__pb2.MarketPlaceFeeRequest.FromString,
                    response_serializer=payout__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteMarketPlaceFees': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMarketPlaceFees,
                    request_deserializer=payout__pb2.DeleteFlatFeeRequest.FromString,
                    response_serializer=payout__pb2.StatusResponse.SerializeToString,
            ),
            'CreatePromotions': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePromotions,
                    request_deserializer=payout__pb2.PromotionsRequest.FromString,
                    response_serializer=payout__pb2.StatusResponse.SerializeToString,
            ),
            'GetPromotions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromotions,
                    request_deserializer=payout__pb2.TenantId.FromString,
                    response_serializer=payout__pb2.PromotionsResponse.SerializeToString,
            ),
            'DeletePromotions': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePromotions,
                    request_deserializer=payout__pb2.DeletePromotion.FromString,
                    response_serializer=payout__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.Payout', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Payout(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFlatFees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/GetFlatFees',
            payout__pb2.TenantId.SerializeToString,
            payout__pb2.FlatFeesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateFlatFees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/CreateFlatFees',
            payout__pb2.FlatFeesRequest.SerializeToString,
            payout__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCalculationAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/GetCalculationAttributes',
            payout__pb2.TenantId.SerializeToString,
            payout__pb2.CalculationAttributesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetParameterValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/GetParameterValue',
            payout__pb2.TenantId.SerializeToString,
            payout__pb2.ParameterValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFlatFees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/DeleteFlatFees',
            payout__pb2.DeleteFlatFeeRequest.SerializeToString,
            payout__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMarketPlaceFees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/GetMarketPlaceFees',
            payout__pb2.TenantId.SerializeToString,
            payout__pb2.MarketPlaceFeeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetColumnsForMarketPlaceFees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/GetColumnsForMarketPlaceFees',
            payout__pb2.TenantId.SerializeToString,
            payout__pb2.ColumnsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMarketPlaceFees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/CreateMarketPlaceFees',
            payout__pb2.MarketPlaceFeeRequest.SerializeToString,
            payout__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMarketPlaceFees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/DeleteMarketPlaceFees',
            payout__pb2.DeleteFlatFeeRequest.SerializeToString,
            payout__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePromotions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/CreatePromotions',
            payout__pb2.PromotionsRequest.SerializeToString,
            payout__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPromotions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/GetPromotions',
            payout__pb2.TenantId.SerializeToString,
            payout__pb2.PromotionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePromotions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Payout/DeletePromotions',
            payout__pb2.DeletePromotion.SerializeToString,
            payout__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
